'use client';
import {Brain,Layers} from 'lucide-react';
import {type Patient,type Workspace} from '@/lib/theranetrix';
import {demoInsights} from '@/lib/demo-insights';
import {Badge,Panel} from './ui';
import {RecommendationDetails} from './recommendation-details';

export function DemoInsights({p,data,onPlan}:{p:Patient;data:Workspace;onPlan?:(text:string)=>void}){
  const insight=demoInsights(p,data);
  return <Panel className="connected-insights" title="Shadow AI + PST · patient review" subtitle="Automatic analysis of this patient’s saved record. Updates when the record changes." action={<Badge tone={insight.enabledShadow||insight.enabledPst?'blue':'neutral'}>{insight.enabledShadow||insight.enabledPst?'Active':'Off'}</Badge>}>
    <div className="demo-insight-summary"><Brain size={22}/><div><strong>Shadow AI summary</strong><p>{insight.summary}</p><RecommendationDetails title="Why this review is suggested" summary={insight.summary} rationale={insight.shadow.filter(item=>item.attention).map(item=>item.detail)} sources={insight.shadow.map(item=>({label:item.title,value:item.basis,href:'/patients/'+encodeURIComponent(p.id)+'?tab=visit'}))} limitations={['Rule version: '+insight.version+'. These record checks are not validated clinical predictions.','Reported changes and medication reports do not establish treatment efficacy.']}/></div></div>
    <div className="demo-insight-columns">{[{name:'PST',icon:Layers,enabled:insight.enabledPst,items:insight.pst,description:'Medication, preferences, and plan'},{name:'Shadow AI',icon:Brain,enabled:insight.enabledShadow,items:insight.shadow,description:'Outcome changes, conflicting reports, and gaps'}].map(engine=><section key={engine.name}><header><engine.icon size={20}/><div><h3>{engine.name}</h3><small>{engine.description}</small></div><Badge>{engine.enabled?'Active':'Off'}</Badge></header>{engine.enabled?engine.items.map(f=><article key={f.id} className={f.attention?'needs-attention':''}><strong>{f.title}</strong><p>{f.detail}</p><RecommendationDetails title={f.title} label="Reason & source" summary={f.detail} rationale={[f.detail]} sources={[{label:'Recorded basis',value:f.basis,href:'/patients/'+encodeURIComponent(p.id)+(f.id.startsWith('med-')||f.id.startsWith('effects-')||f.id.startsWith('use-')||f.id.startsWith('regimen-')||f.id.startsWith('prior-')||f.id.startsWith('duration-')?'?tab=visit#patient-medications':f.id.startsWith('outcome-')?'?tab=twin':f.id==='plan'?'?tab=treatment':'?tab=visit')}]} considerations={f.attention?['This finding is flagged for clinician review. Confirm it with the patient and source record before taking action.']:[]} limitations={['Record-based prototype check, not a prescription or clinical evidence review. Rule version: '+insight.version+'.']}/>{onPlan&&f.attention&&<button className="text-link" onClick={()=>onPlan(`Review focus: ${f.title}\nRecord basis: ${f.detail}\nSource: ${f.basis}\nEngine review · ${insight.version} · record ${insight.revision}`)}>Use in care plan</button>}</article>):<p className="padded muted">This capability or its dependency is turned off.</p>}</section>)}</div>
    <div className="demo-insight-footer"><span>{p.id} · Record {insight.revision} · {insight.version}</span><span>Updated from the current patient record.</span></div>
  </Panel>;
}
