'use client';
import {useRef,useState,type FormEvent} from 'react';
import {MessageSquarePlus,Download} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
import {Badge,formatDate} from './ui';
import type {Context} from './app';
import type {PrototypeFeedback as FeedbackEntry} from '@/lib/theranetrix';

// A request asks the team to review part of the screen. Saving one never hides, removes, or changes anything.
// The same request types, labels and order as the feedback pins (public/feedback-pin/theranetrix-config.js).
export const requests:{value:FeedbackEntry['intent'];label:string}[]=[{value:'Question',label:'Question'},{value:'Keep',label:'Keep as is'},{value:'Hide',label:'Suggest hiding'},{value:'Change',label:'Suggest a change'},{value:'Prioritize',label:'Suggest prioritizing'},{value:'Remove',label:'Suggest removing'}];
// Saved feedback keeps the screen's navigation parameters (tab, workflow and record IDs, the Treatment directory's open=treatment) only, never other text a link may carry.
const routeParams=['tab','workflow','workflowJourney','workflowRecordId','patient','journey','journeyStop','journeyPatient','open'];
export function feedbackRoute(pathname:string,search:string){const params=new URLSearchParams(search);for(const key of [...params.keys()])if(!routeParams.includes(key))params.delete(key);const query=params.toString();return pathname+(query?'?'+query:'');}
const requestLabel=(intent:string)=>requests.find(r=>r.value===intent)?.label??intent;

export function PrototypeFeedback({ctx,path,screen}:{ctx:Context;path:string;screen:string}){
  const [open,setOpen]=useState(false),[text,setText]=useState(''),[priority,setPriority]=useState<'Must-have'|'Nice-to-have'>('Must-have'),[intent,setIntent]=useState<FeedbackEntry['intent']>('Change'),[error,setError]=useState(''),[saved,setSaved]=useState(false);
  const submitting=useRef(false);
  const feedback=ctx.data.prototypeFeedback??[];
  async function submit(event:FormEvent){event.preventDefault();if(ctx.busy||submitting.current||!text.trim())return;submitting.current=true;setError('');setSaved(false);try{const route=feedbackRoute(window.location.pathname,window.location.search);const ok=await ctx.save({type:'prototype.feedback.add',path:route,screen,priority,intent,text},'Prototype feedback saved');if(ok){setText('');setSaved(true);}else setError('Feedback was not saved. Your draft is still here.');}catch(error){setError(error instanceof Error?error.message:'Feedback was not saved.');}finally{submitting.current=false;}}
  function download(){const blob=new Blob([JSON.stringify(feedback,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='theranetrix-prototype-feedback.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <><button aria-label="Feedback on this screen" className="prototype-feedback-trigger" onClick={()=>setOpen(true)}><MessageSquarePlus size={16}/><span>Feedback</span></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="entry-dialog care-entry-dialog feedback-dialog"><DialogHeader><DialogTitle>Feedback on this screen</DialogTitle><DialogDescription>{screen} · Ask a question, or ask the team to keep, hide, change, prioritize or remove part of this screen.</DialogDescription></DialogHeader><p className="subtle-notice" role="note">Review request only. Nothing on screen is hidden or deleted until the team reviews it. Feedback never changes patient records.</p><form onSubmit={submit} className="entry-form care-form"><fieldset disabled={ctx.busy}><div className="feedback-classification"><label>How important<select value={priority} onChange={e=>setPriority(e.target.value as typeof priority)}><option>Must-have</option><option>Nice-to-have</option></select></label><label>Request<select value={intent} onChange={e=>setIntent(e.target.value as typeof intent)}>{requests.map(r=><option key={r.value} value={r.value}>{r.label}</option>)}</select></label></div><label>Your feedback<Textarea required maxLength={3000} rows={4} value={text} onChange={e=>{setText(e.target.value);setSaved(false);}} placeholder="Which part needs to change, and what should happen instead?"/></label>{error&&<p role="alert" className="care-form-error">{error}</p>}{saved&&<p role="status" className="text-teal">Saved to this workspace for review.</p>}<div className="form-actions"><Button type="button" variant="outline" onClick={()=>setOpen(false)}>Close</Button><Button type="submit" disabled={!text.trim()||ctx.busy}>Save feedback</Button></div></fieldset></form><details className="feedback-history"><summary>Feedback recorded here · {feedback.filter(item=>item.path.split('?')[0]===path).length}</summary>{feedback.filter(item=>item.path.split('?')[0]===path).map(item=><article key={item.id}><div><Badge tone={item.priority==='Must-have'?'amber':'neutral'}>{item.priority}</Badge><strong>{requestLabel(item.intent)}</strong></div><p>{item.text}</p><small>{item.author} · {formatDate(item.date,true)}</small></article>)}{feedback.length>0&&<Button variant="outline" onClick={download}><Download size={14}/>Export all feedback</Button>}</details></DialogContent></Dialog></>;
}
