'use client';
import {useState,type FormEvent} from 'react';
import {ArrowUpRight,Plus,Trash2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type Patient} from '@/lib/theranetrix';
import {treatmentCourse,treatmentDirections,goalStatuses,emptyTreatmentReview,type TreatmentOption,type TreatmentReview,type TreatmentReviewFields} from '@/lib/treatment-review';
import {groupMedications} from '@/lib/medication-groups';
import type {Medication} from '@/lib/medications';
import {type Context} from './app';
import {RecommendationDetails} from './recommendation-details';
import {Badge,Panel,Picker,formatDate} from './ui';

/** Stopped medications split by recorded indication, the same groups as current medications. Empty groups are left out. */
export function priorTrialGroups(trials:Medication[]){return groupMedications(trials).filter(group=>group.medications.length>0);}
/** Earlier treatment reviews, newest first: who decided what, and the options discussed at the time. The current review is shown separately. */
export function TreatmentDecisionHistory({history}:{history:TreatmentReview['history']}){
  if(!history.length)return null;
  const rows=[...history].sort((a,b)=>b.date.localeCompare(a.date));
  return <section className="treatment-decision-history" aria-label="Earlier treatment decisions"><h3>Earlier treatment decisions <span>{rows.length}</span></h3><ol>{rows.map((h,i)=><li key={h.date+i}><p className="treatment-decision-history-meta"><time dateTime={h.date}>{formatDate(h.date)}</time> · {h.author} · {h.direction} · Goal: {h.goalStatus}</p><p>{h.decision||'Decision not recorded.'}</p>{h.options.length>0&&<details><summary>Options discussed <span>{h.options.length}</span></summary><ul>{h.options.map((o,j)=><li key={j}><div><strong>{o.title}</strong> <Badge tone={o.status==='Agreed'?'teal':o.status==='Deferred'?'neutral':'amber'}>{o.status}</Badge></div>{o.rationale&&<p>{o.rationale}</p>}{o.considerations&&<small><b>Considerations:</b> {o.considerations}</small>}</li>)}</ul></details>}</li>)}</ol></section>;
}
export function TreatmentCourse({p,ctx}:{p:Patient;ctx:Context}){
  const [open,setOpen]=useState(false),course=treatmentCourse(p,ctx.data),r=course.record;
  return <><Panel className="treatment-course" title="Treatment journey & next decision" action={<button className="text-link" onClick={()=>setOpen(true)}>{r?'Review decision':'Record treatment direction'} <ArrowUpRight size={14}/></button>}>
    <div className="visit-body"><div className="treatment-direction"><Badge tone={course.needsRecheck?'amber':r?.direction==='Monitoring benefit'?'teal':'blue'}>{course.needsRecheck?'New information needs review':course.direction}</Badge>{r&&<small>Recorded {formatDate(r.date)} · {r.author}</small>}</div>
      {r?<><p className="treatment-decision">{r.decision}</p><div className="treatment-goal"><strong>Goal: {course.goalStatus}</strong><p>{course.changedGoal?'The patient goal changed after this review. Update the assessment.':r.goalEvidence||'Goal evidence not recorded.'}</p></div></>:<p>No treatment-direction assessment recorded. Add the patient’s goal progress and the reasoning behind the next step.</p>}
      {course.priorTrials.length>0&&<div className="treatment-trials"><h3>Previously tried</h3>{priorTrialGroups(course.priorTrials).map(group=><div className="treatment-trial-group" role="group" aria-label={'Previously tried · '+group.title} key={group.id}><h4>{group.title} <span>{group.medications.length}</span></h4>{group.medications.map(m=><article key={m.id}><div><strong>{m.name}</strong><span>{m.started?formatDate(m.started):'Start unknown'} → {m.stopped?formatDate(m.stopped):'Stop unknown'}</span></div><p><b>{m.benefit}</b> · {m.stopReason||'Reason for stopping not recorded'}</p>{m.tolerability==='Effects reported'&&<p className="text-rose">Reported effect: {m.effects}</p>}</article>)}</div>)}</div>}
      {r&&<><div className="treatment-options"><h3>Options discussed with the clinician</h3>{r.options.length?r.options.map((o,i)=><article key={i}><div><strong>{o.title}</strong><Badge tone={o.status==='Agreed'?'teal':o.status==='Deferred'?'neutral':'amber'}>{o.status}</Badge></div><p>{o.rationale}</p><small><b>Considerations:</b> {o.considerations}</small><RecommendationDetails title={o.title} label="Recorded reasoning" rationale={[o.rationale||'No rationale was recorded for this option.']} sources={[{label:'Clinician treatment review',value:r.author+' · '+r.direction+'. Discussion outcome: '+o.status,date:r.date},{label:'Goal at review',value:r.goalAtReview||'Goal at review was not recorded.'}]} considerations={[o.considerations||'No additional considerations were recorded.']} limitations={['This is the clinician-entered rationale at that review, not a newly generated recommendation.',...(course.needsRecheck?['The patient record has changed since this assessment. Review current information before acting.']:[])]}/></article>):<p>No discussion options recorded.</p>}</div><div className="treatment-monitoring"><strong>What to monitor</strong><p>{r.monitoring}</p></div><TreatmentDecisionHistory history={r.history}/></>}
    </div></Panel><Dialog open={open} onOpenChange={v=>{if(!v&&!ctx.busy)setOpen(false);}}><DialogContent className="medication-dialog"><DialogHeader><DialogTitle>Treatment review · {p.name}</DialogTitle><DialogDescription>Record clinical reasoning, patient goal progress, and the options discussed. This record does not change a prescription or the scheduled care plan.</DialogDescription></DialogHeader>{open&&<TreatmentForm p={p} ctx={ctx} close={()=>setOpen(false)}/>}</DialogContent></Dialog></>;
}
export function TreatmentForm({p,ctx,close}:{p:Patient;ctx:Context;close:()=>void}){
  const r=p.treatmentReview??emptyTreatmentReview;
  const [reviewedGoal]=useState(p.goal);
  const goalChanged=!!p.treatmentReview&&p.treatmentReview.goalAtReview!==p.goal;
  const [direction,setDirection]=useState(r.direction),[goalStatus,setGoalStatus]=useState(p.treatmentReview?.goalAtReview&&p.treatmentReview.goalAtReview!==p.goal?'Not assessed':r.goalStatus);
  const [options,setOptions]=useState<TreatmentOption[]>(r.options.map(o=>({...o})));
  const update=(index:number,field:keyof TreatmentOption,value:string)=>setOptions(current=>current.map((o,i)=>i===index?{...o,[field]:value}:o));
  async function save(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=new FormData(e.currentTarget);const value=(key:string)=>String(form.get(key)??'').trim();if(await ctx.save({type:'treatment.review',patientId:p.id,expectedGoal:reviewedGoal,direction,goalStatus:goalStatus as TreatmentReviewFields['goalStatus'],goalEvidence:value('goalEvidence'),decision:value('decision'),monitoring:value('monitoring'),options},'Treatment review saved'))close();}
  return <form className="entry-form" onSubmit={save}><fieldset disabled={ctx.busy}><p><strong>Patient goal:</strong> {p.goal}</p><div className="form-two"><label>Treatment direction<Picker label="Treatment direction" value={direction} onChange={v=>setDirection(v as TreatmentReviewFields['direction'])} options={[...treatmentDirections]}/></label><label>Goal progress<Picker label="Goal progress" value={goalStatus} onChange={v=>setGoalStatus(v as TreatmentReviewFields['goalStatus'])} options={[...goalStatuses]}/></label></div><label>Patient evidence for goal progress<Textarea name="goalEvidence" required={goalStatus!=='Not assessed'} defaultValue={goalChanged?'':r.goalEvidence} maxLength={2000} rows={3} placeholder="Record baseline, current ability, target, and the patient's report."/></label><label>Next decision and clinical reasoning<Textarea name="decision" required defaultValue={r.decision} maxLength={2000} rows={3}/></label><h3>Clinician-entered discussion options</h3>{options.map((o,i)=><div className="treatment-option-form" key={i}><div className="form-two"><label>Option title<Input value={o.title} required maxLength={150} onChange={e=>update(i,'title',e.target.value)}/></label><label>Discussion outcome<Picker label={'Option '+(i+1)+' outcome'} value={o.status} onChange={v=>update(i,'status',v)} options={['For discussion','Agreed','Deferred']}/></label></div><label>Reason to consider this option<Textarea required value={o.rationale} maxLength={1000} rows={2} onChange={e=>update(i,'rationale',e.target.value)}/></label><label>Tradeoffs, missing information, and review needed<Textarea required value={o.considerations} maxLength={1000} rows={2} onChange={e=>update(i,'considerations',e.target.value)}/></label><Button type="button" variant="outline" onClick={()=>setOptions(current=>current.filter((_,j)=>j!==i))}><Trash2 size={14}/>Remove option</Button></div>)}{options.length<4&&<Button type="button" variant="outline" onClick={()=>setOptions(current=>[...current,{title:'',status:'For discussion',rationale:'',considerations:''}])}><Plus size={14}/>Add discussion option</Button>}<label>What to monitor and when to review<Textarea name="monitoring" required defaultValue={r.monitoring} maxLength={2000} rows={3}/></label>{p.treatmentReview?<small>Saving keeps the current review, dated, under Earlier treatment decisions.</small>:null}<div className="form-actions"><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button type="submit">{ctx.busy?'Saving…':'Save treatment review'}</Button></div></fieldset></form>;
}

export function DemoCaseLinks({ctx,currentId}:{ctx:Context;currentId?:string}){
  const patients=ctx.data.patients.filter(p=>p.demoCase);
  if(!patients.length)return null;
  return <section className={'demo-case-links'+(currentId?' compact':'')} aria-label="Treatment cases">{patients.map(p=>{const course=treatmentCourse(p,ctx.data);return <a key={p.id} href={'/patients/'+p.id+'?tab=visit'} aria-current={currentId===p.id?'page':undefined}><div><span>{p.demoCase==='finding-treatment'?'Treatment selection':'Improving with follow-up'}</span><ArrowUpRight size={15}/></div><strong>{p.name}</strong><p>{course.needsRecheck?'New information needs review':course.direction}{course.record?' · Goal: '+course.goalStatus:''}</p></a>;})}</section>;
}
