import assert from 'node:assert/strict';
import test from 'node:test';
import {createRequire} from 'node:module';
import {build} from 'esbuild';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';

const bundle=await build({stdin:{contents:"export {seedWorkspace} from './lib/theranetrix';export {plannedDefinitions} from './lib/configuration';export {ConfigurationSettings} from './components/theranetrix/configuration-settings';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'cjs',packages:'external',jsx:'automatic',write:false,plugins:[{name:'css-rendering',setup(builder){builder.onLoad({filter:/\.css$/},()=>({contents:'export default {}',loader:'js'}));}}]});
const mod={exports:{}};new Function('require','module','exports',bundle.outputFiles[0].text)(createRequire(process.cwd()+'/package.json'),mod,mod.exports);
const {seedWorkspace,plannedDefinitions,ConfigurationSettings}=mod.exports;
const html=renderToStaticMarkup(React.createElement(ConfigurationSettings,{ctx:{data:seedWorkspace(),user:'Verified reviewer',busy:false,save:async()=>true,open:()=>{}}}));
const visible=fragment=>fragment.replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/\s+/g,' ').trim();
const coverageRows=[...html.matchAll(/<div class="config-coverage-row">([\s\S]*?)<\/div>/g)].map(match=>visible(match[1]));

test('the Settings feature-coverage roadmap never promises a conversational model',()=>{
 assert.equal(coverageRows.length,12,'every coverage domain is checked');
 for(const row of coverageRows)assert.doesNotMatch(row,/conversational model/i,row);
 assert.ok(coverageRows.some(row=>/Clinician-approved rubric extensions \(versioned\)/.test(row)),'the advisor roadmap names versioned, clinician-approved rubric extensions');
});

test('the Settings coverage and planned-scope copy makes no recommendation or independence claim',()=>{
 for(const row of coverageRows)assert.doesNotMatch(row,/recommendation|independent/i,row);
 const ranked=plannedDefinitions.find(item=>item.id==='treatmentRecommendations');
 assert.equal(ranked.description,'Clinical candidates or ranked options generated by PST or Shadow AI.');
});
