'use client';

import {type FormEvent,type ReactNode,useEffect,useId,useRef,useState} from 'react';
import Link from 'next/link';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {getSummary,monitoringFindings,type Action,type Context,type State,type ProtocolStep,type ProtocolPredicate,type EvidenceSource,type ReadinessGate,type ConfigurationRecord,type ProtocolRecord,type EvidenceRecord,type ReleaseRecord,type OperationRecord,type MonitoringRecord,type ReadinessRecord,type RuntimeScope,type RecoveryReconciliation,type MonitoringFinding,type MonitoringInterval,type MonitoringRule,type RecallRecord,type ProtocolAssignment} from '@/lib/clinical-flows/program-governance';
import {createdGovernanceRecordId} from '@/lib/clinical-flows/governance-ui';
import {Badge,EmptyState,Panel,formatDate} from '../ui';
import styles from './program-governance.module.css';

type Kind='configuration'|'protocol'|'evidence'|'release'|'operation'|'monitoring'|'readiness';
type RecordType=ConfigurationRecord|ProtocolRecord|EvidenceRecord|ReleaseRecord|OperationRecord|MonitoringRecord|ReadinessRecord;
type Draft=Record<string,unknown>;
type Field={key:string;label:string;kind?:'lines'|'textarea'|'date'|'select'|'number';options?:string[];required?:boolean};
type Descriptor={kind:Kind;journey:string;title:string;description:string;records:RecordType[];defaults:Draft;fields:Field[]};
const lines=(value:string)=>value.split('\n').map((item)=>item.trim()).filter(Boolean);
const text=(value:unknown)=>typeof value==='string'?value:'';
const initialStep=():ProtocolStep=>({id:'',title:'',owner:'',kind:'action',prerequisites:[],nextStepIds:[],branchStepIds:[],openQuestion:''});
const initialSource=():EvidenceSource=>({title:'',locator:'',kind:'supporting',publicationDate:'',retracted:false});
const initialGates=():ReadinessGate[]=>[{id:'clinical-evidence',title:'Clinical evidence review',required:true,disposition:'open',evidenceRef:''},{id:'partner-rights',title:'Partner rights review',required:true,disposition:'open',evidenceRef:''}];
const statuses=(record:RecordType)=>'status' in record?record.status:record.decision;
const title=(record:RecordType)=>'title' in record?record.title:record.activity;
const requestId=()=>crypto.randomUUID();
function needsCurrentReview(record:RecordType,state:State){
  const today=new Date().toISOString().slice(0,10);
  const unusable=(evidence:EvidenceRecord)=>evidence.status!=='approved'||!!evidence.rightsExpiry&&evidence.rightsExpiry<=today||!evidence.supportingSources.some((source)=>source.kind==='supporting'&&!source.retracted)||evidence.supportingSources.some((source)=>source.kind==='supporting'&&source.retracted);
  if('supportingSources' in record)return record.status==='approved'&&unusable(record);
  if('reviewRequired' in record&&record.reviewRequired)return true;
  if('evidenceRefIds' in record&&record.evidenceRefIds.some((id)=>{const evidence=state.evidences.find((item)=>item.id===id);return !evidence||unusable(evidence)||record.evidenceVersions[id]!==undefined&&record.evidenceVersions[id]!==evidence.version;}))return true;
  if('configurationId' in record){const configuration=state.configurations.find((item)=>item.id===record.configurationId);return !configuration||configuration.status!=='active'||state.activeConfigurationId!==configuration.id||record.configurationVersion!==undefined&&record.configurationVersion!==configuration.version;}
  return false;
}

function exportJson(name:string,data:unknown){
  const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));
  const link=document.createElement('a');link.href=url;link.download=name;link.click();
  setTimeout(()=>URL.revokeObjectURL(url),1000);
}
function FieldInput({field,value,onChange}:{field:Field;value:unknown;onChange:(value:unknown)=>void}){
  const id=useId();
  const [lineDraft,setLineDraft]=useState(()=>Array.isArray(value)?value.join('\n'):text(value));
  const renderedLines=Array.isArray(value)&&JSON.stringify(lines(lineDraft))!==JSON.stringify(value)?value.join('\n'):lineDraft;
  return <label htmlFor={id}>{field.label}{field.kind==='select'?<select id={id} value={text(value)} onChange={(event)=>onChange(event.target.value)} required={field.required!==false}>{field.options?.map((option)=><option key={option} value={option}>{option}</option>)}</select>:field.kind==='lines'?<Textarea id={id} rows={3} value={renderedLines} onChange={(event)=>{setLineDraft(event.target.value);onChange(lines(event.target.value));}} required={field.required!==false}/>:field.kind==='textarea'?<Textarea id={id} rows={3} value={text(value)} onChange={(event)=>onChange(event.target.value)} required={field.required!==false}/>:<Input id={id} type={field.kind==='date'?'date':field.kind==='number'?'number':'text'} value={typeof value==='number'?String(value):text(value)} onChange={(event)=>onChange(field.kind==='number'?Number(event.target.value):event.target.value)} required={field.required!==false}/>}</label>;
}
function ListEditor<T,>({label,items,create,onChange,children,minimum=1}:{label:string;items:T[];create:()=>T;onChange:(items:T[])=>void;children:(item:T,index:number,update:(next:T)=>void)=>ReactNode;minimum?:number}){
  return <fieldset className={styles.nested}><legend>{label}</legend>{items.map((item,index)=><div className={styles.item} key={index}>{children(item,index,(next)=>onChange(items.map((entry,i)=>i===index?next:entry)))}<Button type="button" variant="outline" size="sm" disabled={items.length<=minimum} onClick={()=>onChange(items.filter((_,i)=>i!==index))}>Remove {label.toLowerCase()} {index+1}</Button></div>)}<Button type="button" variant="outline" onClick={()=>onChange([...items,create()])}>Add {label.toLowerCase()}</Button></fieldset>;
}
function ProtocolSteps({value,onChange}:{value:ProtocolStep[];onChange:(value:ProtocolStep[])=>void}){
  return <ListEditor label="Protocol step" items={value} create={initialStep} onChange={onChange}>{(step,index,update)=><><strong>Step {index+1}</strong>{([{key:'id',label:'Step ID'},{key:'title',label:'Step title'},{key:'owner',label:'Step owner'},{key:'kind',label:'Step type',kind:'select',options:['action','decision','handoff']},{key:'prerequisites',label:'Prerequisite step IDs, one per line',kind:'lines',required:false},{key:'nextStepIds',label:'Next step IDs, one per line',kind:'lines',required:false},{key:'branchStepIds',label:'Branch step IDs, one per line',kind:'lines',required:false},{key:'openQuestion',label:'Open question',kind:'textarea',required:false}] as Field[]).map((field)=><FieldInput key={field.key} field={field} value={step[field.key as keyof ProtocolStep]} onChange={(next)=>update({...step,[field.key]:next})}/>)}<ProtocolExecutionFields step={step} onChange={update}/></>}</ListEditor>;
}
function ProtocolExecutionFields({step,onChange}:{step:ProtocolStep;onChange:(step:ProtocolStep)=>void}){
  const predicate=(kind:ProtocolPredicate['kind']):ProtocolPredicate=>kind==='always'?{kind}:kind==='step-status'?{kind,stepId:'',equals:'completed'}:kind==='event'?{kind,eventType:''}:{kind,choiceId:'',equals:''};
  return <><FieldInput field={{key:'sourceRef',label:'Source instruction reference',required:false}} value={step.sourceRef} onChange={value=>onChange({...step,sourceRef:text(value)||undefined})}/><ListEditor label="Executable transition" items={step.transitions??[]} minimum={0} create={()=>({toStepId:'',when:{kind:'always'} as ProtocolPredicate})} onChange={transitions=>onChange({...step,transitions})}>{(edge,index,update)=><><strong>Transition {index+1}</strong><FieldInput field={{key:'target',label:'Target step ID'}} value={edge.toStepId} onChange={value=>update({...edge,toStepId:text(value)})}/><FieldInput field={{key:'kind',label:'Condition type',kind:'select',options:['always','step-status','event','review-choice']}} value={edge.when.kind} onChange={value=>update({...edge,when:predicate(value as ProtocolPredicate['kind'])})}/>{edge.when.kind==='step-status'&&<FieldInput field={{key:'step',label:'Step that must be completed'}} value={edge.when.stepId} onChange={value=>update({...edge,when:{kind:'step-status',stepId:text(value),equals:'completed'}})}/>} {edge.when.kind==='event'&&<FieldInput field={{key:'event',label:'Recorded event type'}} value={edge.when.eventType} onChange={value=>update({...edge,when:{kind:'event',eventType:text(value)}})}/>} {edge.when.kind==='review-choice'&&<><FieldInput field={{key:'choice',label:'Reviewed choice ID'}} value={edge.when.choiceId} onChange={value=>update({...edge,when:{...edge.when,choiceId:text(value)} as ProtocolPredicate})}/><FieldInput field={{key:'equals',label:'Required recorded choice'}} value={edge.when.equals} onChange={value=>update({...edge,when:{...edge.when,equals:text(value)} as ProtocolPredicate})}/></>}</>}</ListEditor><label className={styles.check}><input type="checkbox" checked={!!step.schedule} onChange={event=>onChange({...step,schedule:event.target.checked?{dueAfterDays:0,channel:'manual',reviewEvidence:''}:undefined})}/>Use a reviewed schedule for this step</label>{step.schedule&&<><FieldInput field={{key:'days',label:'Days after assignment',kind:'number'}} value={step.schedule.dueAfterDays} onChange={value=>onChange({...step,schedule:{...step.schedule!,dueAfterDays:Number(value)}})}/><FieldInput field={{key:'channel',label:'Reviewed communication channel',kind:'select',options:['manual','in-app','phone','email']}} value={step.schedule.channel} onChange={value=>onChange({...step,schedule:{...step.schedule!,channel:value as NonNullable<ProtocolStep['schedule']>['channel']}})}/><FieldInput field={{key:'scheduleEvidence',label:'Schedule review evidence'}} value={step.schedule.reviewEvidence} onChange={value=>onChange({...step,schedule:{...step.schedule!,reviewEvidence:text(value)}})}/></>}</>;
}
const emptyChecks=()=>({sourceVersion:'',rightsEvidence:'',clinicalReview:'',implementationReview:'',fixtureEvidence:'',migrationPolicy:'',rollbackPlan:''});
const emptyScope=():RuntimeScope=>({capabilities:['assessments'],populationRefs:[],permittedRoles:[],inputRefs:[],outputRefs:[],claimRefs:[],environment:'demo'});
const emptyRule=():MonitoringRule=>({id:'',version:'',payer:'',jurisdiction:'',effectiveFrom:'',effectiveTo:'',reviewer:'',evidenceRef:''});
const emptyInterval=():MonitoringInterval=>({startAt:'',endAt:'',sourceEventId:''});
function ReadinessScopeEditor({draft,state,onChange}:{draft:Draft;state:State;onChange:(key:string,value:unknown)=>void}){
  const scope=(draft.scope??emptyScope()) as RuntimeScope,ref=draft.releaseRef as ReadinessRecord['releaseRef'];
  return <fieldset className={styles.nested}><legend>Exact release and permitted scope</legend><label>Release artifact<select required value={ref?`${ref.releaseId}:${ref.artifactVersion}`:''} onChange={event=>{const release=state.releases.find(item=>`${item.id}:${item.artifactVersion}`===event.target.value);onChange('releaseRef',release?{releaseId:release.id,artifactVersion:release.artifactVersion}:undefined);}}><option value="">Choose a release artifact</option>{state.releases.map(release=><option key={release.id} value={`${release.id}:${release.artifactVersion}`}>{release.title} · artifact {release.artifactVersion} · {release.decision}</option>)}</select></label>{ref&&<p>Pinned artifact {ref.artifactVersion}. Later release content changes require a new review.</p>}{([{key:'capabilities',label:'Permitted capabilities, one per line',kind:'lines'},{key:'populationRefs',label:'Population scope references, one per line',kind:'lines'},{key:'permittedRoles',label:'Permitted roles, one per line',kind:'lines'},{key:'inputRefs',label:'Permitted input references, one per line',kind:'lines'},{key:'outputRefs',label:'Permitted output references, one per line',kind:'lines'},{key:'claimRefs',label:'Permitted claim references, one per line',kind:'lines'}] as Field[]).map(field=><FieldInput key={field.key} field={field} value={scope[field.key as keyof RuntimeScope]} onChange={value=>onChange('scope',{...scope,[field.key]:value})}/>)}<p>Environment: demo. Recorded reviews do not authorize production use.</p></fieldset>;
}
function MonitoringServiceEditor({draft,patients,onChange}:{draft:Draft;patients:readonly {id:string;name:string}[];onChange:(key:string,value:unknown)=>void}){
  const rule=(draft.ruleRef??emptyRule()) as MonitoringRule;
  return <fieldset className={styles.nested}><legend>Timed service and scoped rule</legend><label>Service patient<select required value={text(draft.patientId)} onChange={event=>onChange('patientId',event.target.value)}><option value="">Select patient</option>{patients.map(patient=><option key={patient.id} value={patient.id}>{patient.name}</option>)}</select></label><FieldInput field={{key:'performerId',label:'Actual performer'}} value={draft.performerId} onChange={value=>onChange('performerId',value)}/><FieldInput field={{key:'serviceCode',label:'Service code or named service'}} value={draft.serviceCode} onChange={value=>onChange('serviceCode',value)}/><ListEditor label="Service interval" items={(draft.intervals as MonitoringInterval[])??[emptyInterval()]} create={emptyInterval} onChange={value=>onChange('intervals',value)}>{(interval,index,update)=><><strong>Interval {index+1}</strong>{[{key:'startAt',label:'Start timestamp with timezone'},{key:'endAt',label:'End timestamp with timezone'},{key:'sourceEventId',label:'Original activity event ID'}].map(field=><FieldInput key={field.key} field={field} value={interval[field.key as keyof MonitoringInterval]} onChange={value=>update({...interval,[field.key]:text(value)})}/>)}</>}</ListEditor>{([{key:'id',label:'Rule identity'},{key:'version',label:'Rule version'},{key:'payer',label:'Payer or named demo payer'},{key:'jurisdiction',label:'Jurisdiction'},{key:'effectiveFrom',label:'Effective from',kind:'date'},{key:'effectiveTo',label:'Effective through',kind:'date'},{key:'reviewer',label:'Rule reviewer'},{key:'evidenceRef',label:'Dated rule review evidence'}] as Field[]).map(field=><FieldInput key={field.key} field={field} value={rule[field.key as keyof MonitoringRule]} onChange={value=>onChange('ruleRef',{...rule,[field.key]:text(value)})}/>)}</fieldset>;
}
function MonitoringFindingsEditor({value,onChange}:{value:MonitoringFinding[];onChange:(value:MonitoringFinding[])=>void}){
  return <fieldset className={styles.nested}><legend>Documentation and overlapping time findings</legend>{!value.length&&<p>No findings in the current record inventory.</p>}{value.map((finding,index)=><div key={finding.id} className={styles.item}><strong>{finding.description}</strong>{([{key:'owner',label:'Assigned reviewer'},{key:'disposition',label:'Finding disposition',kind:'select',options:['open','resolved','not-applicable']},{key:'evidenceRef',label:'Resolution evidence',required:finding.disposition!=='open'}] as Field[]).map(field=><FieldInput key={field.key} field={field} value={finding[field.key as keyof MonitoringFinding]} onChange={next=>onChange(value.map((item,i)=>i===index?{...item,[field.key]:next}:item))}/>)}</div>)}</fieldset>;
}
function EvidenceSources({value,onChange}:{value:EvidenceSource[];onChange:(value:EvidenceSource[])=>void}){
  return <ListEditor label="Source" items={value} create={initialSource} onChange={onChange}>{(source,index,update)=><><strong>Source {index+1}</strong>{([{key:'title',label:'Source title'},{key:'locator',label:'Exact source locator'},{key:'kind',label:'Source relationship',kind:'select',options:['supporting','conflicting']},{key:'publicationDate',label:'Publication date',kind:'date'}] as Field[]).map((field)=><FieldInput key={field.key} field={field} value={source[field.key as keyof EvidenceSource]} onChange={(next)=>update({...source,[field.key]:next})}/>)}<label className={styles.check}><input type="checkbox" checked={source.retracted} onChange={(event)=>update({...source,retracted:event.target.checked})}/>Source has been retracted</label></>}</ListEditor>;
}
function Gates({value,onChange,allowAdd=false}:{value:ReadinessGate[];onChange:(value:ReadinessGate[])=>void;allowAdd?:boolean}){
  return <fieldset className={styles.nested}><legend>Required readiness gates</legend>{value.map((gate,index)=><div className={styles.item} key={index}><strong>{gate.title} ({gate.required?'required':'optional'})</strong>{allowAdd&&<><FieldInput field={{key:'id',label:'Gate ID'}} value={gate.id} onChange={(next)=>onChange(value.map((entry,i)=>i===index?{...entry,id:text(next)}:entry))}/><FieldInput field={{key:'title',label:'Gate title'}} value={gate.title} onChange={(next)=>onChange(value.map((entry,i)=>i===index?{...entry,title:text(next)}:entry))}/></>}<FieldInput field={{key:'disposition',label:`${gate.title} disposition`,kind:'select',options:['open','satisfied','waived']}} value={gate.disposition} onChange={(next)=>onChange(value.map((entry,i)=>i===index?{...entry,disposition:next as ReadinessGate['disposition']}:entry))}/><FieldInput field={{key:'evidenceRef',label:`${gate.title} review or waiver evidence`,required:gate.disposition!=='open'}} value={gate.evidenceRef} onChange={(next)=>onChange(value.map((entry,i)=>i===index?{...entry,evidenceRef:text(next)}:entry))}/></div>)}{allowAdd&&<Button type="button" variant="outline" onClick={()=>onChange([...value,{id:'',title:'New required gate',required:true,disposition:'open',evidenceRef:''}])}>Add required gate</Button>}</fieldset>;
}
function History({record}:{record:RecordType}){
  return <details><summary>History and previous versions ({record.history.length})</summary><ol className={styles.history}>{record.history.map((entry)=><li key={entry.id}><strong>{entry.from} → {entry.to}</strong><p>{entry.reason}</p><small>{entry.actor} · {formatDate(entry.at,true)}{entry.evidenceRef?` · ${entry.evidenceRef}`:''}</small></li>)}</ol>{record.revisions.length>0&&<Button type="button" variant="outline" size="sm" onClick={()=>exportJson(`governance-${record.id}-versions.json`,record.revisions)}>Export previous versions</Button>}</details>;
}
function recordDraft(descriptor:Descriptor,record?:RecordType):Draft{
  if(!record)return structuredClone(descriptor.defaults);
  return Object.fromEntries(Object.keys(descriptor.defaults).map((key)=>[key,structuredClone((record as unknown as Draft)[key]??descriptor.defaults[key])]));
}
function DraftEditor({descriptor,record,state,patients,busy,onAction}:{descriptor:Descriptor;record?:RecordType;state:State;patients:readonly {id:string;name:string}[];busy:boolean;onAction:(action:Action)=>Promise<boolean>}){
  const [draft,setDraft]=useState<Draft>(()=>recordDraft(descriptor,record));
  const update=(key:string,value:unknown)=>setDraft((current)=>({...current,[key]:value}));
  const immutable=!!record&&(descriptor.kind==='configuration'&&['active','inactive'].includes(statuses(record))||descriptor.kind==='evidence'&&statuses(record)==='withdrawn'||descriptor.kind==='operation'&&statuses(record)==='closed');
  async function submit(event:FormEvent<HTMLFormElement>){
    event.preventDefault();
    const payload={...draft};
    if(descriptor.kind==='evidence'&&!payload.rightsExpiry)delete payload.rightsExpiry;
    const type=descriptor.kind==='operation'?'program-governance.operation-report':descriptor.kind==='monitoring'?'program-governance.monitoring-record-service':`program-governance.${descriptor.kind}-save-draft`;
    const action={type,requestId:requestId(),...(record&&!immutable?{id:record.id,expectedVersion:record.version}:{}),record:payload} as Action;
    await onAction(action);
  }
  return <form onSubmit={submit} className={styles.form}><fieldset disabled={busy}><legend>{record?immutable?'Create a new draft from this record':`Edit ${title(record)}`:'Create a new record'}</legend>{record&&<p>Version {record.version}. Saving changes requires a new review.{immutable?' This record is retained; your changes create a separate record.':''}</p>}{descriptor.fields.map((field)=><FieldInput key={field.key} field={field} value={draft[field.key]} onChange={(value)=>update(field.key,value)}/>)}{descriptor.kind==='protocol'&&<ProtocolSteps value={draft.steps as ProtocolStep[]} onChange={(value)=>update('steps',value)}/>} {descriptor.kind==='evidence'&&<EvidenceSources value={draft.supportingSources as EvidenceSource[]} onChange={(value)=>update('supportingSources',value)}/>} {descriptor.kind==='release'&&<fieldset className={styles.nested}><legend>Evaluation</legend>{[{key:'agreementSummary',label:'Agreement summary'},{key:'performanceSummary',label:'Performance evidence summary'},{key:'limitations',label:'Limitations'}].map((field)=><FieldInput key={field.key} field={{...field,kind:'textarea'}} value={(draft.evaluation as Draft)[field.key]} onChange={(value)=>update('evaluation',{...(draft.evaluation as Draft),[field.key]:value})}/>)}</fieldset>}{descriptor.kind==='readiness'&&<Gates value={draft.mandatoryGates as ReadinessGate[]} onChange={(value)=>update('mandatoryGates',value)} allowAdd={!record}/>}
    {descriptor.kind==='protocol'&&<fieldset className={styles.nested}><legend>Publication review records</legend>{Object.keys(emptyChecks()).map(key=><FieldInput key={key} field={{key,label:key.replace(/([A-Z])/g,' $1')}} value={(draft.publicationChecks as Draft)?.[key]} onChange={value=>update('publicationChecks',{...(draft.publicationChecks as Draft),[key]:value})}/>)}</fieldset>}
    {descriptor.kind==='readiness'&&<ReadinessScopeEditor draft={draft} state={state} onChange={update}/>}
    {descriptor.kind==='monitoring'&&<MonitoringServiceEditor draft={draft} patients={patients} onChange={update}/>}
    <Button type="submit">{record&&!immutable?'Save revised draft':descriptor.kind==='operation'?'Record operation':descriptor.kind==='monitoring'?'Record monitoring documentation':`Save ${descriptor.kind} draft`}</Button></fieldset></form>;
}

type TransitionFields={reason:string;reviewer:string;evidenceRef:string;conditions:string[];gates:ReadinessGate[];patientId:string;encounterId:string;owner:string;severity:OperationRecord['severity'];findings:MonitoringFinding[]};
type Command={label:string;reviewer?:boolean;evidence?:boolean;conditions?:boolean;gates?:boolean;assignment?:boolean;operation?:boolean;findings?:boolean;build:(fields:TransitionFields)=>Action};
function commandsFor(kind:Kind,record:RecordType,state:State):Command[]{
  const base={id:record.id,expectedVersion:record.version};
  switch(kind){
    case 'configuration':{
      const current=record as ConfigurationRecord;
      if(current.status==='draft')return [{label:'Record configuration review',build:(f)=>({type:'program-governance.configuration-review',requestId:requestId(),...base,reviewNote:f.reason})}];
      if(current.status==='reviewed')return [{label:'Activate configuration',build:(f)=>({type:'program-governance.configuration-activate',requestId:requestId(),...base,reason:f.reason})}];
      if(current.status==='active')return [{label:'Deactivate configuration',build:(f)=>({type:'program-governance.configuration-deactivate',requestId:requestId(),...base,reason:f.reason})}];return [];
    }
    case 'protocol':{
      const current=record as ProtocolRecord;
      if(current.status==='draft'||current.status==='changes-required')return [{label:'Request protocol review',build:(f)=>({type:'program-governance.protocol-request-review',requestId:requestId(),...base,reason:f.reason})}];
      if(current.status==='review-requested')return (['reviewed','changes-required'] as const).map((outcome)=>({label:`Record protocol ${outcome}`,reviewer:true,evidence:true,build:(f)=>({type:'program-governance.protocol-record-review',requestId:requestId(),...base,outcome,reviewer:f.reviewer,evidenceLocator:f.evidenceRef,reason:f.reason})}));
      if(current.status==='reviewed')return [{label:'Record protocol publication',evidence:true,build:(f)=>({type:'program-governance.protocol-record-publication',requestId:requestId(),...base,evidenceRef:f.evidenceRef,reason:f.reason})}];
      if(current.status==='publication-recorded')return [{label:'Assign published protocol to episode',assignment:true,build:(f)=>({type:'program-governance.protocol-assign-episode',requestId:requestId(),patientId:f.patientId,encounterId:f.encounterId,protocolId:record.id,expectedProtocolVersion:record.version,expectedAssignmentVersion:state.protocolAssignments.find((assignment)=>assignment.patientId===f.patientId&&assignment.encounterId===f.encounterId)?.version??0,reason:f.reason})},{label:'Retire protocol',evidence:true,build:(f)=>({type:'program-governance.protocol-retire',requestId:requestId(),...base,evidenceRef:f.evidenceRef,reason:f.reason})}];return [];
    }
    case 'evidence':{
      const current=record as EvidenceRecord;
      const commands:Command[]=[];
      if(current.status==='draft'||current.status==='changes-required')commands.push({label:'Request evidence review',build:(f)=>({type:'program-governance.evidence-request-review',requestId:requestId(),...base,reason:f.reason})});
      if(current.status==='review-requested')for(const outcome of ['approved','changes-required'] as const)commands.push({label:`Record evidence ${outcome}`,reviewer:true,build:(f)=>({type:'program-governance.evidence-record-review',requestId:requestId(),...base,outcome,reviewer:f.reviewer,reason:f.reason})});
      if(current.status!=='withdrawn')commands.push({label:'Withdraw evidence',build:(f)=>({type:'program-governance.evidence-withdraw',requestId:requestId(),...base,reason:f.reason})});return commands;
    }
    case 'release':return [
      ...(['approved','conditional-review','no-go'] as const).map((decision):Command=>({label:`Record release ${decision}`,reviewer:true,conditions:true,build:(f)=>({type:'program-governance.release-record-review',requestId:requestId(),...base,reviewer:f.reviewer,decision,unresolvedConditions:f.conditions,reason:f.reason})})),
      {label:'Record rollout observation',build:(f)=>({type:'program-governance.release-record-rollout',requestId:requestId(),...base,note:f.reason})},
      {label:'Record rollback observation',build:(f)=>({type:'program-governance.release-record-rollback',requestId:requestId(),...base,note:f.reason})},
    ];
    case 'operation':{
      const current=record as OperationRecord;
      if(current.status==='reported')return [{label:'Confirm operation report',operation:true,build:(f)=>({type:'program-governance.operation-confirm',requestId:requestId(),...base,owner:f.owner,severity:f.severity,reason:f.reason})}];
      if(current.status==='confirmed')return [{label:'Record operation review',evidence:true,build:(f)=>({type:'program-governance.operation-review',requestId:requestId(),...base,evidenceRef:f.evidenceRef,reason:f.reason})}];
      if(current.status==='reviewed')return [{label:'Close operation record',evidence:true,build:(f)=>({type:'program-governance.operation-close',requestId:requestId(),...base,evidenceRef:f.evidenceRef,reason:f.reason})}];return [];
    }
    case 'monitoring':return [...(statuses(record)!=='exported'?(['accept','reject','clarify'] as const).map((decision):Command=>({label:`Record monitoring ${decision}`,findings:true,build:f=>({type:'program-governance.monitoring-record-decision',requestId:requestId(),...base,decision,findings:f.findings,reason:f.reason})})):[]),...((record as MonitoringRecord).decision==='accept'?[{label:'Record reviewed package export',evidence:true,build:(f:TransitionFields):Action=>({type:'program-governance.monitoring-export',requestId:requestId(),...base,evidenceRef:f.evidenceRef})}]:[])];
    case 'readiness':return (['proposed','conditional-review','no-go'] as const).map((decision)=>({label:`Record readiness ${decision}`,reviewer:true,evidence:true,conditions:true,gates:true,build:(f)=>({type:'program-governance.readiness-record-decision',requestId:requestId(),...base,reviewer:f.reviewer,decision,blockingConditions:f.conditions,mandatoryGates:f.gates,reviewEvidence:f.evidenceRef,reason:f.reason})}));
  }
}
function TransitionEditor({kind,record,state,patientId,patients,busy,onAction}:{kind:Kind;record:RecordType;state:State;patientId?:string;patients:readonly {id:string;name:string}[];busy:boolean;onAction:(action:Action)=>Promise<boolean>}){
  const commands=commandsFor(kind,record,state);
  const [selected,setSelected]=useState('');
  const [confirmed,setConfirmed]=useState(false);
  const [fields,setFields]=useState<TransitionFields>({reason:'',reviewer:'',evidenceRef:'',conditions:'unresolvedConditions' in record?[...record.unresolvedConditions]:'blockingConditions' in record?[...record.blockingConditions]:[],gates:'mandatoryGates' in record?structuredClone(record.mandatoryGates):[],patientId:patientId??'',encounterId:'',findings:kind==='monitoring'?monitoringFindings(state,record as MonitoringRecord):[],owner:'owner' in record?record.owner:'',severity:'severity' in record?record.severity:'medium'});
  const command=commands.find((item)=>item.label===selected);
  const update=(key:keyof TransitionFields,value:unknown)=>{setConfirmed(false);setFields((current)=>({...current,[key]:value}));};
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!command||!confirmed)return;const ok=await onAction(command.build(fields));if(ok){setConfirmed(false);setSelected('');}}
  if(!commands.length)return <p>No further transitions are available for this record. Its history remains available below.</p>;
  return <form className={styles.form} onSubmit={submit}><fieldset disabled={busy}><legend>Record a transition</legend><label>Action<select value={selected} onChange={(event)=>{setSelected(event.target.value);setConfirmed(false);}} required><option value="">Choose an action</option>{commands.map((item)=><option key={item.label} value={item.label}>{item.label}</option>)}</select></label>{command&&<>
    <p><strong>{command.label}</strong> for {title(record)}, version {record.version}.</p>
    {command.assignment&&<label>Episode patient<select value={fields.patientId} required onChange={(event)=>update('patientId',event.target.value)}><option value="">Select a patient</option>{patients.map((patient)=><option value={patient.id} key={patient.id}>{patient.name}</option>)}</select></label>}
    {command.assignment&&<FieldInput field={{key:'encounterId',label:'Episode encounter ID'}} value={fields.encounterId} onChange={value=>update('encounterId',value)}/>}
    {command.findings&&<MonitoringFindingsEditor value={fields.findings} onChange={value=>update('findings',value)}/>}
    {command.reviewer&&<FieldInput field={{key:'reviewer',label:'Named reviewer'}} value={fields.reviewer} onChange={(value)=>update('reviewer',value)}/>}
    {command.evidence&&<FieldInput field={{key:'evidenceRef',label:'Review, publication, or closure evidence'}} value={fields.evidenceRef} onChange={(value)=>update('evidenceRef',value)}/>}
    {command.operation&&<><FieldInput field={{key:'owner',label:'Confirmed owner'}} value={fields.owner} onChange={(value)=>update('owner',value)}/><FieldInput field={{key:'severity',label:'Confirmed severity',kind:'select',options:['low','medium','high','critical']}} value={fields.severity} onChange={(value)=>update('severity',value)}/></>}
    {command.conditions&&<FieldInput field={{key:'conditions',label:'Remaining blockers, one per line',kind:'lines',required:false}} value={fields.conditions} onChange={(value)=>update('conditions',value)}/>}
    {command.gates&&<Gates value={fields.gates} onChange={(value)=>update('gates',value)}/>}
    <FieldInput field={{key:'reason',label:'Reason and supporting review notes',kind:'textarea'}} value={fields.reason} onChange={(value)=>update('reason',value)}/>
    <label className={styles.check}><input type="checkbox" checked={confirmed} required onChange={(event)=>setConfirmed(event.target.checked)}/>I confirm this record, version, and transition. The record reflects the supplied review; it does not deploy, authorize, bill, or clinically validate a service.</label>
    <Button type="submit" disabled={!confirmed}>Confirm {command.label.toLowerCase()}</Button>
  </>}</fieldset></form>;
}
function ConfirmedForm({label,busy,children,onSubmit}:{label:string;busy:boolean;children:ReactNode;onSubmit:()=>Promise<boolean>}){
  const [confirmed,setConfirmed]=useState(false);
  return <form className={styles.form} onChangeCapture={()=>setConfirmed(false)} onSubmit={async event=>{event.preventDefault();if(confirmed&&await onSubmit())setConfirmed(false);}}><fieldset disabled={busy}><legend>{label}</legend>{children}<label className={styles.check}><input type="checkbox" required checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/>I reviewed the selected record, version, affected work, and supplied evidence.</label><Button type="submit" disabled={!confirmed}>{label}</Button></fieldset></form>;
}
function RecoveryEditor({record,busy,onAction}:{record:OperationRecord;busy:boolean;onAction:(action:Action)=>Promise<boolean>}){
  const [draft,setDraft]=useState<RecoveryReconciliation>(()=>structuredClone(record.reconciliation??{expectedEventManifestRef:'',reconciliationEvidence:'',events:[],coverage:[],correctiveActions:[],remainingRisks:[],reviewer:''}));
  const [reason,setReason]=useState('');
  if(record.status==='closed')return <p>Recovery reconciliation is retained with the closed operation.</p>;
  return <details><summary>Reconcile missing events and clinical coverage</summary><ConfirmedForm label="Save recovery reconciliation" busy={busy} onSubmit={()=>onAction({type:'program-governance.operation-reconcile',requestId:requestId(),id:record.id,expectedVersion:record.version,record:draft,reason})}><p>{draft.events.filter(item=>item.status==='missing').length} missing events · {draft.coverage.filter(item=>!item.acceptedBy||!item.evidenceRef).length} unaccepted coverage obligations. A reviewed manifest is required even when no events are missing.</p>{([{key:'expectedEventManifestRef',label:'Expected event manifest reference'},{key:'reconciliationEvidence',label:'Reconciliation evidence'},{key:'reviewer',label:'Named reconciliation reviewer'},{key:'correctiveActions',label:'Corrective actions, one per line',kind:'lines',required:false},{key:'remainingRisks',label:'Remaining risks, one per line',kind:'lines',required:false}] as Field[]).map(field=><FieldInput key={field.key} field={field} value={draft[field.key as keyof RecoveryReconciliation]} onChange={value=>setDraft({...draft,[field.key]:value})}/>)}<ListEditor label="Expected downstream event" items={draft.events} minimum={0} create={():RecoveryReconciliation['events'][number]=>({eventId:'',service:'',owner:'',status:'missing',sourceReceipt:'',evidenceRef:''})} onChange={events=>setDraft({...draft,events})}>{(item,index,update)=><><strong>Expected event {index+1}</strong>{([{key:'eventId',label:'Expected event identity'},{key:'service',label:'Downstream service'},{key:'owner',label:'Reconciliation owner'},{key:'status',label:'Reconciliation disposition',kind:'select',options:['missing','replayed','duplicate-disposed','not-required']},{key:'sourceReceipt',label:'Replay or duplicate receipt',required:item.status==='replayed'||item.status==='duplicate-disposed'},{key:'evidenceRef',label:'Event disposition evidence',required:item.status!=='missing'}] as Field[]).map(field=><FieldInput key={field.key} field={field} value={item[field.key as keyof typeof item]} onChange={value=>update({...item,[field.key]:value})}/>)}</>}</ListEditor><ListEditor label="Coverage obligation" items={draft.coverage} minimum={0} create={()=>({obligationId:'',owner:'',acceptedBy:'',evidenceRef:''})} onChange={coverage=>setDraft({...draft,coverage})}>{(item,index,update)=><><strong>Coverage {index+1}</strong>{[{key:'obligationId',label:'Pending work or coverage identity'},{key:'owner',label:'Receiving owner'},{key:'acceptedBy',label:'Named acceptance',required:false},{key:'evidenceRef',label:'Acceptance evidence',required:false}].map(field=><FieldInput key={field.key} field={field} value={item[field.key as keyof typeof item]} onChange={value=>update({...item,[field.key]:value})}/>)}</>}</ListEditor><FieldInput field={{key:'reason',label:'Reconciliation reason',kind:'textarea'}} value={reason} onChange={value=>setReason(text(value))}/></ConfirmedForm></details>;
}
function RecallReview({record,busy,onAction}:{record:RecallRecord;busy:boolean;onAction:(action:Action)=>Promise<boolean>}){
  const [operation,setOperation]=useState('review-impact'),[impactId,setImpactId]=useState(record.impacts[0]?.id??''),[disposition,setDisposition]=useState<'reviewed-no-change'|'reviewed-plan-amended'|'accepted-transfer'>('reviewed-no-change');
  const [evidenceRef,setEvidence]=useState(''),[reason,setReason]=useState(''),[acceptedBy,setAccepted]=useState(''),[planRef,setPlan]=useState('');
  const base={requestId:requestId(),id:record.id,expectedVersion:record.version,evidenceRef,reason};
  return <div className={styles.record}><p>Subject: {record.subject.kind} {record.subject.id} · version {record.subject.kind==='release'?record.subject.artifactVersion:record.subject.version}. New use remains suspended after patient reviews close.</p><p>Impact mapping: {record.usageCoverage}. Owner: {record.owner}. {record.impacts.filter(impact=>impact.disposition==='pending').length} pending reviews.</p><ul>{record.impacts.map(impact=><li key={impact.id}><Link href={`/patients/${encodeURIComponent(impact.patientId)}?workflow=decisions`}>{impact.patientId}</Link> · {impact.sourceId} v{impact.sourceVersion} · {impact.owner} · {impact.disposition}{impact.evidenceRef?` · ${impact.evidenceRef}`:''}</li>)}</ul>{record.status==='open'&&<ConfirmedForm label="Record recall review" busy={busy} onSubmit={()=>onAction(operation==='review-impact'?{...base,type:'program-governance.recall-review-impact',impactId,disposition,...(acceptedBy?{acceptedBy}:{}),...(planRef?{planRef}:{})}:operation==='review-coverage'?{...base,type:'program-governance.recall-review-coverage'}:{...base,type:'program-governance.recall-close'})}><FieldInput field={{key:'action',label:'Recall review action',kind:'select',options:['review-impact','review-coverage','close']}} value={operation} onChange={value=>setOperation(text(value))}/>{operation==='review-impact'&&<><label>Affected output<select required value={impactId} onChange={event=>setImpactId(event.target.value)}><option value="">Select affected output</option>{record.impacts.map(impact=><option key={impact.id} value={impact.id}>{impact.patientId} · {impact.sourceId} · {impact.disposition}</option>)}</select></label><FieldInput field={{key:'disposition',label:'Patient review disposition',kind:'select',options:['reviewed-no-change','reviewed-plan-amended','accepted-transfer']}} value={disposition} onChange={value=>setDisposition(value as typeof disposition)}/>{disposition==='accepted-transfer'&&<FieldInput field={{key:'acceptedBy',label:'Receiving owner who accepted'}} value={acceptedBy} onChange={value=>setAccepted(text(value))}/>} {disposition==='reviewed-plan-amended'&&<FieldInput field={{key:'planRef',label:'Reviewed amended plan reference'}} value={planRef} onChange={value=>setPlan(text(value))}/>}</>}<FieldInput field={{key:'evidence',label:'Review evidence'}} value={evidenceRef} onChange={value=>setEvidence(text(value))}/><FieldInput field={{key:'reason',label:'Review reason',kind:'textarea'}} value={reason} onChange={value=>setReason(text(value))}/></ConfirmedForm>}<details><summary>Recall history</summary><ol>{record.history.map(item=><li key={item.id}>{item.actor}: {item.reason} · {item.at}</li>)}</ol></details></div>;
}
function RecallPanel({state,busy,onAction}:{state:State;busy:boolean;onAction:(action:Action)=>Promise<boolean>}){
  const [kind,setKind]=useState<'release'|'evidence'>('release'),[subjectId,setSubject]=useState(''),[version,setVersion]=useState(1),[owner,setOwner]=useState(''),[reason,setReason]=useState(''),[evidenceRef,setEvidence]=useState(''),[selectedId,setSelected]=useState('');
  const candidates=kind==='release'?state.releases:state.evidences,subject=candidates.find(item=>item.id===subjectId),selected=state.recalls.find(item=>item.id===selectedId)??state.recalls[0];
  return <Panel title="Model and evidence recall" subtitle="Suspend exact artifacts, identify affected saved outputs, and assign patient review without rewriting prior decisions."><details><summary>Open a recall and suspend new use</summary><ConfirmedForm label="Open artifact recall" busy={busy} onSubmit={async()=>subject?onAction({type:'program-governance.recall-open',requestId:requestId(),subject:kind==='release'?{kind,id:subject.id,artifactVersion:version}:{kind,id:subject.id,version},expectedSubjectVersion:subject.version,owner,reason,evidenceRef}):false}><FieldInput field={{key:'kind',label:'Artifact type',kind:'select',options:['release','evidence']}} value={kind} onChange={value=>{setKind(value as typeof kind);setSubject('');}}/><label>Artifact record<select required value={subjectId} onChange={event=>{setSubject(event.target.value);const item=candidates.find(entry=>entry.id===event.target.value);if(item)setVersion('artifactVersion' in item?item.artifactVersion:item.version);}}><option value="">Select artifact</option>{candidates.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select></label><FieldInput field={{key:'version',label:'Exact artifact or evidence version',kind:'number'}} value={version} onChange={value=>setVersion(Number(value))}/><FieldInput field={{key:'owner',label:'Recall review owner'}} value={owner} onChange={value=>setOwner(text(value))}/><FieldInput field={{key:'evidence',label:'Recall evidence'}} value={evidenceRef} onChange={value=>setEvidence(text(value))}/><FieldInput field={{key:'reason',label:'Recall reason',kind:'textarea'}} value={reason} onChange={value=>setReason(text(value))}/></ConfirmedForm></details>{state.recalls.length>0?<><label>Recall record<select value={selected?.id??''} onChange={event=>setSelected(event.target.value)}>{state.recalls.map(item=><option key={item.id} value={item.id}>{item.subject.kind} {item.subject.id} · {item.status}</option>)}</select></label>{selected&&<RecallReview key={`${selected.id}-${selected.version}`} record={selected} busy={busy} onAction={onAction}/>}</>:<p>No artifact recalls recorded.</p>}</Panel>;
}
function MigrationForm({assignment,state,patientPathways,busy,onAction}:{assignment:ProtocolAssignment;state:State;patientPathways?:Context['patientPathways'];busy:boolean;onAction:(action:Action)=>Promise<boolean>}){
  const [targetId,setTarget]=useState(''),[reason,setReason]=useState(''),[evidenceRef,setEvidence]=useState('');
  const [stageMap,setMap]=useState<NonNullable<ProtocolAssignment['migration']>['stageMap']>([]),[pendingWork,setWork]=useState<NonNullable<ProtocolAssignment['migration']>['pendingWork']>(()=>(assignment.protocolSnapshot?.steps??[]).map(step=>({oldStepId:step.id,disposition:'transfer',owner:step.owner,evidenceRef:''})));
  const target=state.protocols.find(item=>item.id===targetId),episode=patientPathways?.find(item=>item.protocolAssignmentId===assignment.id); 
  return <ConfirmedForm label="Migrate protocol assignment" busy={busy} onSubmit={async()=>target?onAction({type:'program-governance.protocol-migrate-episode',requestId:requestId(),id:assignment.id,expectedVersion:assignment.version,...(episode?.version?{expectedEpisodeVersion:episode.version}:{}),targetProtocolId:target.id,expectedProtocolVersion:target.version,stageMap,pendingWork:pendingWork.map(({acceptedBy,...work})=>acceptedBy?{...work,acceptedBy}:work),reason,evidenceRef}):false}><p>Source protocol {assignment.protocolId} v{assignment.protocolVersion}. This operation preserves the prior assignment and requires a disposition for open work.</p>{episode&&<p>Reviewed episode version {episode.version}: {episode.stages.map(step=>`${step.id}: ${step.status} (${step.owner})`).join('; ')}.</p>}<label>Published target<select required value={targetId} onChange={event=>{setTarget(event.target.value);setMap([]);}}><option value="">Select published target</option>{state.protocols.filter(item=>item.status==='publication-recorded'&&(item.id!==assignment.protocolId||item.version!==assignment.protocolVersion)).map(item=><option key={item.id} value={item.id}>{item.title} v{item.version}</option>)}</select></label>{pendingWork.map((work,index)=>{const mapping=stageMap.find(item=>item.oldStepId===work.oldStepId);return <fieldset key={work.oldStepId} className={styles.nested}><legend>Source step {work.oldStepId}</legend><label>Target step mapping<select value={mapping?.newStepId??''} onChange={event=>setMap([...stageMap.filter(item=>item.oldStepId!==work.oldStepId),...(event.target.value?[{oldStepId:work.oldStepId,newStepId:event.target.value,carryStatus:false}]:[])])}><option value="">No target mapping</option>{target?.steps.map(step=><option key={step.id} value={step.id}>{step.title}</option>)}</select></label>{mapping&&<label className={styles.check}><input type="checkbox" checked={mapping.carryStatus} onChange={event=>setMap(stageMap.map(item=>item.oldStepId===work.oldStepId?{...item,carryStatus:event.target.checked}:item))}/>Carry the saved source status</label>}{([{key:'disposition',label:'Open work disposition',kind:'select',options:['carry','complete','transfer']},{key:'owner',label:'Responsible owner'},{key:'evidenceRef',label:'Disposition evidence'},{key:'acceptedBy',label:'Receiving owner acceptance',required:work.disposition==='transfer'}] as Field[]).map(field=><FieldInput key={field.key} field={field} value={work[field.key as keyof typeof work]} onChange={value=>setWork(pendingWork.map((item,i)=>i===index?{...item,[field.key]:value}:item))}/>)}</fieldset>})}<FieldInput field={{key:'evidence',label:'Migration review evidence'}} value={evidenceRef} onChange={value=>setEvidence(text(value))}/><FieldInput field={{key:'reason',label:'Migration reason',kind:'textarea'}} value={reason} onChange={value=>setReason(text(value))}/></ConfirmedForm>;
}
function MigrationPanel({state,patientPathways,busy,onAction}:{state:State;patientPathways?:Context['patientPathways'];busy:boolean;onAction:(action:Action)=>Promise<boolean>}){
  const [id,setId]=useState(''),assignment=state.protocolAssignments.find(item=>item.id===id)??state.protocolAssignments[0];
  return <Panel title="Protocol episode migration" subtitle="Existing episodes remain on their pinned publication until migration accounts for their open work.">{assignment?<><label>Assigned episode<select value={assignment.id} onChange={event=>setId(event.target.value)}>{state.protocolAssignments.map(item=><option key={item.id} value={item.id}>{item.patientId} · {item.encounterId??'Legacy episode'} · protocol v{item.protocolVersion}</option>)}</select></label><MigrationForm key={`${assignment.id}-${assignment.version}-${patientPathways?.find(item=>item.protocolAssignmentId===assignment.id)?.version??0}`} assignment={assignment} state={state} patientPathways={patientPathways} busy={busy} onAction={onAction}/></>:<p>Assign a published protocol to an episode to begin.</p>}</Panel>;
}
function GovernanceSection({descriptor,state,patientId,patients,busy,onAction}:{descriptor:Descriptor;state:State;patientId?:string;patients:readonly {id:string;name:string}[];busy:boolean;onAction:(action:Action)=>Promise<boolean>}){
  const [selection,setSelection]=useState<{id:string;requestId?:string;created?:boolean}>({id:descriptor.records[0]?.id??''});
  const createdId=createdGovernanceRecordId(state,descriptor.kind,selection.requestId);
  const selectedId=createdId??selection.id;
  const selected=descriptor.records.find((record)=>record.id===selectedId);
  const recordHeading=useRef<HTMLHeadingElement>(null);
  if(createdId)setSelection({id:createdId,created:true});
  const createdSelectionId=selection.created?selection.id:undefined;
  useEffect(()=>{
    if(createdSelectionId)recordHeading.current?.focus();
  },[createdSelectionId]);
  async function saveDraft(action:Action){
    const createsRecord=!('id' in action&&action.id);
    if(createsRecord)setSelection(current=>({id:current.id,requestId:action.requestId}));
    const saved=await onAction(action);
    if(!saved&&createsRecord)setSelection(current=>current.requestId===action.requestId?{id:current.id}:current);
    return saved;
  }
  const reviewRequired=selected?needsCurrentReview(selected,state):false;
  return <Panel title={descriptor.title} subtitle={descriptor.description}><div className={styles.section}><label className={styles.selector}>Select {descriptor.kind} record<select value={selectedId} disabled={busy} onChange={(event)=>setSelection({id:event.target.value})}><option value="">Create new record</option>{descriptor.records.map((record)=><option key={record.id} value={record.id}>{title(record)} · {statuses(record)} · v{record.version}</option>)}</select></label>
    {selected&&<div className={styles.record}><h3 ref={recordHeading} tabIndex={-1}>{title(selected)} · version {selected.version}</h3>{(createdId||selection.created)&&<p role="status">Created and selected {title(selected)}. Choose an action below to continue its review.</p>}<Badge tone={reviewRequired?'rose':statuses(selected)==='approved'||statuses(selected)==='active'||statuses(selected)==='publication-recorded'?'teal':'amber'}>{reviewRequired?'review-required':statuses(selected)}</Badge><p>Record ID: <code>{selected.id}</code></p><p>Updated {formatDate(selected.updatedAt,true)}</p>{reviewRequired&&<p role="status">The recorded status is {statuses(selected)}. Its evidence or configuration is no longer current; a new review is required.</p>}{'sampleNotice' in selected&&<p>{selected.sampleNotice}</p>}{'regulatoryAuthorizationNote' in selected&&<p>{selected.regulatoryAuthorizationNote}</p>}{'bridge' in selected&&selected.bridge.notes.map((note)=><p key={note}>{note}</p>)}<TransitionEditor key={`transition-${selected.id}-${selected.version}`} kind={descriptor.kind} record={selected} state={state} patientId={patientId} patients={patients} busy={busy} onAction={onAction}/>{descriptor.kind==='operation'&&<RecoveryEditor key={`recovery-${selected.id}-${selected.version}`} record={selected as OperationRecord} busy={busy} onAction={onAction}/>}<History record={selected}/>{descriptor.kind==='monitoring'&&(selected as MonitoringRecord).exportRecords.length>0&&<Button type="button" variant="outline" disabled={busy} onClick={()=>exportJson(`monitoring-${selected.id}-reviewed-package.json`,(selected as MonitoringRecord).exportRecords[0])}>Download reviewed monitoring package</Button>}<Button type="button" variant="outline" size="sm" disabled={busy} onClick={()=>exportJson(`governance-${selected.id}.json`,selected)}>Export selected record</Button></div>}
    <details open={!selected}><summary>{selected?'Edit or copy record':'New record details'}</summary><DraftEditor key={`draft-${selected?.id??'new'}-${selected?.version??0}`} descriptor={descriptor} record={selected} state={state} patients={patients} busy={busy} onAction={saveDraft}/></details>
    {!descriptor.records.length?<EmptyState title="No records yet" description="Save a draft, then select it to review, revise, and record transitions."/>:<p>{descriptor.records.length} records available. Select a record to continue its workflow.</p>}
  </div></Panel>;
}

export function ProgramGovernancePanel({patientId,patients,state,patientPathways,busy,onAction}:{patientId?:string;patients:readonly {id:string;name:string}[];state:State;patientPathways?:Context['patientPathways'];busy:boolean;onAction:(action:Action)=>Promise<boolean>}){
  const [notice,setNotice]=useState('');
  const [error,setError]=useState('');
  const [saving,setSaving]=useState(false);
  const [now,setNow]=useState(()=>new Date().toISOString());
  const inFlight=useRef(false);
  useEffect(()=>{const timer=setInterval(()=>setNow(new Date().toISOString()),60000);return()=>clearInterval(timer);},[]);
  const summary=getSummary(state,patientId,now);
  async function submit(action:Action){
    if(inFlight.current||busy)return false;
    inFlight.current=true;setSaving(true);setError('');setNotice('');
    try{const ok=await onAction(action);if(ok)setNotice('Governance record saved.');else setError('The record was not saved. Your draft is retained; review the reported issue and try again.');return ok;}catch(cause){setError(cause instanceof Error?cause.message:'The record was not saved. Your draft is retained.');return false;}finally{inFlight.current=false;setSaving(false);}
  }
  const descriptors:Descriptor[]=[
    {kind:'configuration',journey:'J22',title:'Program configuration',description:'Review capability settings and preserve non-hideable safety essentials.',records:state.configurations,defaults:{title:'',capabilityChoices:['assessments','messages'],allowedCadence:['weekly'],languages:['English'],communicationSettings:['in-app'],displayReferences:[],safetyEssentials:['Visible safety disclaimer','Named reviewer'],nonHideableSafetyEssentials:['Visible safety disclaimer','Named reviewer'],reviewNote:''},fields:[{key:'title',label:'Configuration title'},{key:'capabilityChoices',label:'Capability choices, one per line: assessments, reviewPrompts, digitalTwin, pst, shadow, advisor, pathways, messages',kind:'lines'},{key:'allowedCadence',label:'Allowed cadence, one per line: daily, weekly, monthly, quarterly, manual-only',kind:'lines'},{key:'languages',label:'Languages, one per line',kind:'lines'},{key:'communicationSettings',label:'Communication channels, one per line: in-app, phone, email, interpreter, proxy',kind:'lines'},{key:'displayReferences',label:'Display references, one per line',kind:'lines',required:false},{key:'safetyEssentials',label:'Visible safety essentials, one per line',kind:'lines'},{key:'nonHideableSafetyEssentials',label:'Non-hideable safety essentials, one per line',kind:'lines'},{key:'reviewNote',label:'Draft notes',kind:'textarea',required:false}]},
    {kind:'protocol',journey:'J23',title:'Protocol authoring',description:'Author an operational protocol, resolve questions, record review and publication, then assign a published version.',records:state.protocols,defaults:{title:'',owner:'',evidenceLocator:'',unresolvedQuestions:[],steps:[initialStep()],publicationChecks:emptyChecks()},fields:[{key:'title',label:'Protocol title'},{key:'owner',label:'Protocol owner'},{key:'evidenceLocator',label:'Protocol evidence locator'},{key:'unresolvedQuestions',label:'Unresolved questions, one per line',kind:'lines',required:false}]},
    {kind:'evidence',journey:'J24',title:'Evidence and content registry',description:'Record exact sources, rights, dates, and translations. Evidence changes invalidate dependent reviews.',records:state.evidences,defaults:{title:'',indication:'',population:'',endpoint:'',supportingSources:[initialSource()],rights:'public-summary',rightsExpiry:'',instrumentVersion:'',approvedTranslation:'',reviewNote:''},fields:[{key:'title',label:'Evidence title'},{key:'indication',label:'Indication'},{key:'population',label:'Population'},{key:'endpoint',label:'Endpoint'},{key:'rights',label:'Rights basis',kind:'select',options:['owned','licensed','public-summary']},{key:'rightsExpiry',label:'Rights expiry date (unavailable from this date)',kind:'date',required:false},{key:'instrumentVersion',label:'Instrument version',required:false},{key:'approvedTranslation',label:'Translation approval reference',required:false},{key:'reviewNote',label:'Evidence notes',kind:'textarea',required:false}]},
    {kind:'release',journey:'J25',title:'Release registry',description:'Keep exact release metadata, evaluation, decisions, and observed rollout or rollback records.',records:state.releases,defaults:{title:'',modelId:'',softwareId:'',configurationId:state.activeConfigurationId??'',intendedUse:'',evidenceRefIds:[],modelClaims:[],evaluation:{agreementSummary:'',performanceSummary:'',limitations:''},unresolvedConditions:[],overrideTrainingPolicy:'Manual review only'},fields:[{key:'title',label:'Release title'},{key:'modelId',label:'Model ID'},{key:'softwareId',label:'Software ID'},{key:'configurationId',label:'Active configuration record ID'},{key:'intendedUse',label:'Intended use',kind:'textarea'},{key:'evidenceRefIds',label:'Evidence record IDs, one per line',kind:'lines',required:false},{key:'modelClaims',label:'Model claims, one per line',kind:'lines',required:false},{key:'unresolvedConditions',label:'Unresolved conditions, one per line',kind:'lines',required:false},{key:'overrideTrainingPolicy',label:'Override training policy'}]},
    {kind:'operation',journey:'J26',title:'Operations',description:'Record incident or restore-exercise evidence, owner confirmation, review, and closure.',records:state.operations,defaults:{title:'',kind:'incident',affectedServices:[],owner:'',severity:'medium',actionsTaken:[],evidenceRef:'',restoreOutcome:'not-applicable'},fields:[{key:'title',label:'Operation title'},{key:'kind',label:'Operation kind',kind:'select',options:['incident','restore-proof']},{key:'affectedServices',label:'Affected services, one per line',kind:'lines'},{key:'owner',label:'Operation owner'},{key:'severity',label:'Severity',kind:'select',options:['low','medium','high','critical']},{key:'actionsTaken',label:'Reported actions, one per line',kind:'lines',required:false},{key:'evidenceRef',label:'Operation evidence locator'},{key:'restoreOutcome',label:'Reported restore outcome (use not-applicable for incidents)',kind:'select',options:['not-applicable','reported-success','reported-failure']}]},
    {kind:'monitoring',journey:'J27',title:'Monitoring documentation',description:'Document actual service activity and qualified review. Billing eligibility needs external payer and legal review.',records:state.monitoring,defaults:{serviceDate:now.slice(0,10),activity:'',source:'',evidenceRef:'',missingDocumentation:[],patientId:'',performerId:'',serviceCode:'',intervals:[emptyInterval()],ruleRef:emptyRule()},fields:[{key:'serviceDate',label:'Service date',kind:'date'},{key:'activity',label:'Service activity'},{key:'source',label:'Documentation source'},{key:'evidenceRef',label:'Monitoring evidence locator'},{key:'missingDocumentation',label:'Missing documentation, one per line',kind:'lines',required:false}]},
    {kind:'readiness',journey:'J28',title:'Release readiness',description:'Review claims, partner obligations, required gates, and evidence before recording a readiness decision.',records:state.readiness,defaults:{title:'',functions:[],claims:[],partnerAssets:[],partnerRights:[],partnerResponsibilities:[],evidenceRefIds:[],blockingConditions:[],mandatoryGates:initialGates(),releaseRef:undefined,scope:emptyScope()},fields:[{key:'title',label:'Readiness title'},{key:'functions',label:'Functions, one per line',kind:'lines'},{key:'claims',label:'Claims, one per line',kind:'lines'},{key:'partnerAssets',label:'Partner assets, one per line',kind:'lines',required:false},{key:'partnerRights',label:'Partner rights, one per line',kind:'lines',required:false},{key:'partnerResponsibilities',label:'Partner responsibilities, one per line',kind:'lines',required:false},{key:'evidenceRefIds',label:'Supporting evidence record IDs, one per line',kind:'lines',required:false},{key:'blockingConditions',label:'Blocking conditions, one per line',kind:'lines',required:false}]},
  ];
  const assignment=state.protocolAssignments.find((record)=>record.patientId===patientId);
  const openRecalls=state.recalls.filter(record=>record.status==='open').length;
  const firstReview=descriptors.find(descriptor=>descriptor.records.some(record=>needsCurrentReview(record,state)))?.kind;
  return <div className={styles.panel+' clinical-governance-editor'}><Panel title="Program governance" subtitle="Review program settings, evidence, releases, and ongoing responsibilities."><div className={styles.section}><Badge tone={summary.overdue?'rose':summary.open?'amber':'teal'}>{summary.open} open · {summary.overdue} overdue</Badge><p>Open a registry to review its records. Saved reviews document supplied evidence; they do not deploy or authorize clinical use.</p>{patientId&&<p>Patient context: {patients.find((patient)=>patient.id===patientId)?.name??patientId}{assignment?` · Assigned protocol version ${assignment.protocolVersion}`:''}</p>}{assignment?.protocolSnapshot&&<details><summary>Assigned protocol snapshot</summary><p>{assignment.protocolSnapshot.title} · version {assignment.protocolVersion}</p><ol>{assignment.protocolSnapshot.steps.map((step)=><li key={step.id}>{step.title} · {step.owner}</li>)}</ol></details>}{summary.attention.length>0&&<div className={styles.attention}><strong>Attention</strong><ul>{summary.attention.map((item)=><li key={item}>{item}</li>)}</ul></div>}<div className={styles.actions}><Button variant="outline" size="sm" disabled={busy||saving} onClick={()=>exportJson('program-governance.json',state)}>Export all governance records</Button><Button variant="outline" size="sm" disabled={busy||saving} onClick={()=>exportJson('program-governance-approvals.json',{configurations:state.configurations,releases:state.releases,readiness:state.readiness})}>Export approval-related records</Button></div><p role="status" aria-live="polite">{notice}</p>{error&&<p role="alert" className={styles.error}>{error}</p>}<p className="clinical-proof-note"><strong>External proof still required:</strong> partner and legal approvals, actual deployment or restore verification, payer review, and clinical validation.</p></div></Panel>
    <details className="clinical-workflow-step" open={openRecalls>0}><summary><span>Model and evidence recalls<small>Suspended artifacts and affected patient reviews</small></span><b className={openRecalls?'clinical-attention-count':''}>{openRecalls} open</b></summary><div className="clinical-step-body"><RecallPanel state={state} busy={busy||saving} onAction={submit}/></div></details>
    <details className="clinical-workflow-step"><summary><span>Protocol transitions<small>Review assignments, version changes, and open work</small></span><b>{state.protocolAssignments.length} assignments</b></summary><div className="clinical-step-body"><MigrationPanel state={state} patientPathways={patientPathways} busy={busy||saving} onAction={submit}/></div></details>
    <div className="clinical-registry-list">{descriptors.map(descriptor=>{const needsReview=descriptor.records.filter(record=>needsCurrentReview(record,state)).length;return <details className="clinical-workflow-step" key={descriptor.kind} open={!openRecalls&&descriptor.kind===(firstReview??'configuration')}><summary data-journey={descriptor.journey}><span>{descriptor.title}<small>{descriptor.description}</small></span><b className={needsReview?'clinical-attention-count':''}>{needsReview?needsReview+' need review':descriptor.records.length+' records'}</b></summary><div className="clinical-step-body"><GovernanceSection descriptor={descriptor} state={state} patientId={patientId} patients={patients} busy={busy||saving} onAction={submit}/></div></details>;})}</div>
  </div>;
}
