import type {Patient,Workspace} from './theranetrix';
import type {Medication} from './medications';
import type {TreatmentReview} from './treatment-review';
import {demoIdentity} from './demo-identity';

const author='Dr. Maya Chen';
const dates=['2026-07-28','2026-08-04','2026-08-11','2026-08-18','2026-08-25','2026-09-01','2026-09-08'];
const reviewed='2026-09-08T11:00:00Z';
const findingId='TN-DEMO-01',improvingId='TN-DEMO-02';
export const treatmentCaseIds=[findingId,improvingId] as const;

function medication(id:string,name:string,changes:Partial<Medication>):Medication{
  return {id,name,regimen:'',indication:'Recorded pain treatment',status:'Active',started:'',benefit:'Not assessed',tolerability:'Not assessed',adherence:'Not assessed',effects:'',reportedAt:'2026-09-08',source:'Patient report',reviewedAt:reviewed,reviewedBy:author,history:[],...changes};
}
function assessment(goal:string,fields:Omit<TreatmentReview,'date'|'author'|'goalAtReview'|'history'>):TreatmentReview{
  return {...fields,date:reviewed,author,goalAtReview:goal,history:[]};
}
export function treatmentDemoCases():Workspace{
  const findingGoal='Complete a 30-minute desk task without stopping because of pain or grogginess';
  const improvingGoal='Walk with my dog for 20 minutes, at least five days each week';
  const finding:Patient={id:findingId,name:'Emma Carter',initials:'EC',age:52,...demoIdentity(findingId),pronouns:'she / her',condition:'Postherpetic neuralgia',stage:'Clinical review',status:'Needs review',clinician:'Dr. Maya Chen',color:'#faecd8',enrolled:dates[0],nextVisit:'2026-09-10',goal:findingGoal,baseline:7,pain:[7,7,6,6,6,6,6],sleep:[3,3,4,4,4,5,5],function:[3,3,4,4,4,4,4],dates:[...dates],adherence:0,completed:['intake','baseline'],pathway:'Chronic pain follow-up',demoCase:'finding-treatment',
    medications:[medication('demo-01-current','Gabapentin',{indication:'Postherpetic neuralgia',regimen:'300 mg orally three times daily',started:'2026-07-28',regimenSince:'2026-08-11',benefit:'Partly helpful',tolerability:'Effects reported',effects:'Morning grogginess interferes with concentration. Patient reports no falls.',adherence:'Taken as recorded',history:[{name:'Gabapentin',regimen:'300 mg orally three times daily',status:'Active',started:'2026-07-28',indication:'Postherpetic neuralgia',benefit:'Partly helpful',tolerability:'Effects reported',effects:'Morning grogginess interferes with concentration.',adherence:'Taken as recorded',reportedAt:'2026-09-01',date:'2026-09-01T11:00:00Z',author}]}),medication('demo-01-prior','Topical lidocaine',{regimen:'Prior application schedule not captured',started:'2026-07-01',stopped:'2026-07-21',stopReason:'Patient reported little relief and local skin irritation; discontinuation recorded by the prior clinician.',status:'Stopped',benefit:'No benefit',tolerability:'Effects reported',effects:'Local skin irritation reported during the trial.',adherence:'Taken as recorded',reportedAt:'2026-07-21'})],
    carePlans:[{id:'demo-01-plan',date:reviewed,author,text:'Discuss whether the reported relief is worth the grogginess and remaining interference with work. Review the prior topical trial and complete medication and clinical-data checks before considering a different treatment. No medication change is recorded in this plan.',owner:'Dr. Maya Chen',followup:'2026-09-10',time:'10:30'}],
    clinicalContext:{allergyStatus:'Not reviewed',allergies:'',medicalHistory:'Shingles six months ago followed by persistent right-sided thoracic pain. Outside medical records and current renal function are not available.',priorTreatments:'Prior topical trial is recorded in the medication history. Work pacing and comfortable clothing provide limited reported relief.',painLocation:'Right thoracic area at the prior shingles site',painDuration:'Six months',physicalContext:'Clothing sensitivity and pain interrupt desk work. Reports about 10 minutes of concentration before a break.',psychologicalContext:'Frustrated by slow progress. Wants to remain alert during the workday.',socialContext:'Works from home; partner can help with appointments.',coordinator:'Taylor Reed, RN',preferences:'Alertness and ability to work matter as much as pain reduction. Prefers to discuss an alternative if grogginess continues.',date:reviewed,author,history:[]},
    treatmentReview:assessment(findingGoal,{direction:'Finding a treatment',goalStatus:'Partly met',goalEvidence:'At intake, about 5 minutes of desk work before a break. Now reports 10 minutes; target is 30 minutes. Pain remains 6/10 and grogginess limits concentration.',decision:'Clarify the benefit versus treatment burden before choosing the next medication strategy.',monitoring:'Recorded plan: weekly pain, function, sleep, and concentration reports; discuss ongoing grogginess at the September 10 visit. Automated reminders are not configured.',options:[{title:'Review the current gabapentin trial',status:'For discussion',rationale:'Partial relief is reported, but the work goal remains unmet.',considerations:'Grogginess, complete medication reconciliation, allergy review, and missing clinical records need clinician assessment.'},{title:'Discuss an alternative medication',status:'For discussion',rationale:'The patient would prefer a different approach if the current burden remains unacceptable.',considerations:'No alternative has been selected, ranked, or prescribed. Review suitability and the prior trial before deciding.'}]}),
    checkins:[],notes:[{id:'demo-01-note',date:reviewed,author,type:'Visit summary',text:'A modest symptom improvement has not restored the patient’s desired function. Current regimen unchanged since August 11. No automatic prescribing recommendation.'}]};
  const improving:Patient={id:improvingId,name:'Lucas Hayes',initials:'LH',age:60,...demoIdentity(improvingId),pronouns:'he / him',condition:'Painful diabetic peripheral neuropathy',stage:'Follow-up',status:'On track',clinician:'Dr. Maya Chen',color:'#e1f1e9',enrolled:dates[0],nextVisit:'2026-09-22',goal:improvingGoal,baseline:8,pain:[8,7,6,5,4,3,3],sleep:[3,4,4,5,6,7,7],function:[2,3,4,5,6,7,8],dates:[...dates],adherence:0,completed:['intake','baseline','review','plan'],pathway:'Chronic pain follow-up',demoCase:'improving',
    medications:[medication('demo-02-current','Duloxetine',{indication:'Painful diabetic peripheral neuropathy',regimen:'60 mg orally once daily',started:'2026-07-28',regimenSince:'2026-08-04',benefit:'Helpful',tolerability:'No effects reported',adherence:'Taken as recorded',history:[{name:'Duloxetine',regimen:'60 mg orally once daily',status:'Active',started:'2026-07-28',indication:'Painful diabetic peripheral neuropathy',benefit:'Helpful',tolerability:'No effects reported',effects:'',adherence:'Taken as recorded',reportedAt:'2026-09-01',date:'2026-09-01T11:00:00Z',author}]}),medication('demo-02-prior','Gabapentin',{regimen:'Prior dose and schedule not available',started:'2026-06-01',stopped:'2026-07-20',stopReason:'Prior clinician documented an end to the trial after persistent daytime grogginess and limited reported benefit.',status:'Stopped',benefit:'Partly helpful',tolerability:'Effects reported',effects:'Daytime grogginess during the prior trial.',adherence:'Taken as recorded',reportedAt:'2026-07-20'})],
    carePlans:[{id:'demo-02-plan',date:reviewed,author,text:'At the recorded review, the patient preferred to retain the current treatment plan because daily activities and reported comfort had improved. Review whether benefit and tolerability remain acceptable at the next follow-up. Complete outside-record reconciliation; this note does not issue a prescription.',owner:'Taylor Reed, RN',followup:'2026-09-22',time:'09:00'}],
    clinicalContext:{allergyStatus:'None reported',allergies:'',medicalHistory:'Type 2 diabetes and chronic pain in both feet. Diabetes medications, laboratory values, and outside records require reconciliation with primary care; they are not imported into this pain-treatment example.',priorTreatments:'Prior gabapentin trial is recorded in the medication history. Patient also reports paced walking and a regular sleep routine.',painLocation:'Both feet',painDuration:'Eighteen months',physicalContext:'Walking tolerance has improved from about 5 minutes to 20 minutes. Residual tingling after longer walks.',psychologicalContext:'More confident leaving home for daily activities.',socialContext:'Lives with spouse and enjoys walking the dog.',coordinator:'Taylor Reed, RN',preferences:'Keep the current routine if benefit and tolerability remain acceptable. Wants to maintain walking and sleep gains.',date:reviewed,author,history:[]},
    treatmentReview:assessment(improvingGoal,{direction:'Monitoring benefit',goalStatus:'Met',goalEvidence:'At intake, 5-minute walks. Patient now reports 20-minute walks on five days in the last week, meeting the recorded goal. Tingling still occurs after longer walks.',decision:'Confirm that the reported benefit is sustained and the treatment burden remains acceptable.',monitoring:'Recorded plan: weekly pain, function, sleep, side-effect, and walking reports. Care-team review on September 22; patient can request earlier review for concerns. Automated monitoring is not connected.',options:[{title:'Maintain the recorded plan with follow-up',status:'Agreed',rationale:'The patient reports helpful treatment, no current side effects, and improved walking toward the goal.',considerations:'Reconfirm current use and patient preferences at follow-up. This is a recorded clinician decision, not an automated safety clearance.'},{title:'Revisit the treatment strategy',status:'Deferred',rationale:'Keep this discussion available if benefit falls, side effects arise, or the patient’s goals change.',considerations:'No additional medication has been selected. Review new information with the prescriber.'}]}),
    checkins:[],notes:[{id:'demo-02-note',date:reviewed,author,type:'Visit summary',text:'Patient reports meaningful functional gains alongside helpful medication, paced walking, and a sleep routine. These observations do not isolate the medication’s effect.'}]};
  for(const p of [finding,improving]){
    p.checkins=dates.map((date,i)=>({id:p.id+'-checkin-'+i,date:date+'T08:00:00Z',pain:p.pain[i],sleep:p.sleep[i],function:p.function[i],note:i===dates.length-1?(p.id===findingId?'The pain is a little less, but I still feel groggy in the morning and can only focus on work for about 10 minutes.':'I walked the dog for 20 minutes on five days this week. The medicine feels helpful and I have not noticed side effects.'):'',source:'Patient self-report' as const})).reverse();
    for(const m of p.medications)m.history.unshift({name:m.name,regimen:m.regimen,status:m.status,started:m.started,indication:m.indication,benefit:m.benefit,tolerability:m.tolerability,adherence:m.adherence,effects:m.effects,reportedAt:m.reportedAt,date:m.reviewedAt,author:m.reviewedBy,regimenSince:m.regimenSince,stopped:m.stopped,stopReason:m.stopReason});
  }
  return {patients:[finding,improving],reviews:[{id:'demo-01-concern',patientId:findingId,title:'Partial relief with ongoing grogginess',detail:'Emma wants to discuss a treatment she can tolerate while working. Review the current trial, prior topical treatment, unknown allergy status, and missing outside records before the next decision.',priority:'High',source:'Patient check-in',status:'Open',created:'2026-09-08T08:30:00Z'}],tasks:[{id:'medication-followup-'+findingId,patientId:findingId,title:'Treatment review',date:'2026-09-10',time:'10:30',type:'Video visit',owner:'Dr. Maya Chen',done:false},{id:'medication-followup-'+improvingId,patientId:improvingId,title:'Treatment review',date:'2026-09-22',time:'09:00',type:'Phone call',owner:'Taylor Reed, RN',done:false}],messages:[{id:'demo-01-message',patientId:findingId,text:finding.checkins[0].note,date:'2026-09-08T08:15:00Z',sender:finding.name,direction:'in'},{id:'demo-02-message',patientId:improvingId,text:improving.checkins[0].note,date:'2026-09-08T08:15:00Z',sender:improving.name,direction:'in'},{id:'demo-02-reply',patientId:improvingId,text:'Your update is recorded for the planned follow-up. Please use the care-team conversation if there are changes you want to discuss.',date:'2026-09-08T10:00:00Z',sender:'Taylor Reed, RN',direction:'out'}],audit:[],features:{reviewPrompts:true,assessments:true,digitalTwin:true,pst:true,shadow:true,advisor:true,pathways:true,messages:true}};
}

// Append the two requested fictional cases once, without replacing existing patient data.
export function ensureTreatmentDemoCases(w:Workspace){
  if(w.demoCasesVersion===1){
    const emma=w.patients.find(p=>p.id==='TN-DEMO-01');
    if(emma?.preferredLanguage==='es')emma.preferredLanguage='en';
    w.demoCasesVersion=2;
    return w;
  }
  if(w.demoCasesVersion===2)return w;
  const samples=treatmentDemoCases();
  for(const p of samples.patients){
    if(w.patients.some(existing=>existing.id===p.id))continue;
    w.patients.push(p);
    w.reviews.push(...samples.reviews.filter(r=>r.patientId===p.id));
    w.tasks.push(...samples.tasks.filter(t=>t.patientId===p.id));
    w.messages.push(...samples.messages.filter(m=>m.patientId===p.id));
  }
  w.demoCasesVersion=2;
  return w;
}
