import {visitObservations} from './visit-observations';
import type {Patient,Workspace} from './theranetrix';
import {activeMedications,type Suggestion} from './medications';

/** Trace the existing workflow rule to the exact records it inspected. No clinical inference. */
export function patientRecommendationBasis(p:Patient,w:Workspace,s:Suggestion){
  const href='/patients/'+encodeURIComponent(p.id);
  const sources:{label:string;value:string;href?:string;date?:string}[]=[];
  const predicates:Record<string,(m:Patient['medications'][number])=>boolean>={
    'Review reported side effects':m=>m.tolerability==='Effects reported',
    'Reassess reported benefit':m=>m.benefit==='No benefit',
    'Clarify medication use':m=>m.adherence==='Missed doses'||m.adherence==='Not taking',
    'Ask about benefit and tolerability':m=>m.benefit==='Not assessed'||m.tolerability==='Not assessed',
    'Discuss remaining symptoms and goals':m=>m.benefit==='Partly helpful',
    'Confirm dose and schedule':m=>!m.regimen,
    'Confirm how medication is being taken':m=>m.adherence==='Not assessed',
  };
  if(s.kind==='medication'){
    const match=predicates[s.title];
    for(const m of activeMedications(p).filter(m=>match?match(m):false))sources.push({label:m.name+' · '+m.source,date:m.reportedAt||undefined,href:href+'?tab=visit#patient-medications',value:`Benefit: ${m.benefit}. Tolerability: ${m.tolerability}${m.effects?'; '+m.effects:''}. Use: ${m.adherence}. Regimen: ${m.regimen||'Not recorded'}. Clinician review: ${m.reviewedAt||'Not recorded'}.`});
    if(s.title==='Reconcile the medication list')sources.push({label:'Medication reconciliation',value:'No active entries and no confirmation of no current medications.',href:href+'?tab=visit#patient-medications'});
  }
  if(s.title==='Review the latest symptom change'&&w.features.assessments){
    const points=visitObservations(p).slice(-2);for(const [index,point] of points.entries())for(const [label,key] of [['Pain','pain'],['Function','function']] as const)sources.push({label:label+(index===points.length-1?' · latest report':' · prior report'),value:point[key]===null?(point.statuses?.[key]??'Not recorded'):point[key]+'/10',date:point.date,href:href+'?tab=twin'});
  }
  const review=w.reviews.find(r=>r.patientId===p.id&&r.title===s.title&&r.detail===s.reason);
  if(review)sources.push({label:review.source+' · '+review.priority+' priority',value:review.detail+' Status: '+review.status,date:review.created,href:href+'?tab=visit'});
  if(s.kind==='plan'){
    sources.push({label:'Patient goal',value:p.goal||'Not recorded',href:href+'?tab=visit#patient-goal'});
    const plan=p.carePlans[0];sources.push({label:'Latest care plan',value:plan?.text||'No care plan recorded',date:plan?.date,href:href+'?tab=visit#visit-plan'});
  }
  if(s.title==='Collect a first outcome check-in')sources.push({label:'Outcome collection',value:'No recorded outcome reports are available. Confirm with the patient before requesting a first report.',href:href+'?tab=twin'});
  return {rationale:[s.reason,'This is a record-based review prompt. It highlights information for the clinician to confirm with the patient.'],sources,considerations:['Confirm whether these reports still describe the patient’s current situation. Record the assessment and agreed next step.'],alternatives:['If the concern has already been addressed, document that assessment and update the relevant record instead of changing treatment.'],limitations:['Generated by the existing patient-review-v1 workflow rules. This is not a prescribing recommendation, a validated risk score, or a literature-based clinical judgment.','Patient reports and overall outcome changes do not establish medication efficacy or causality.']};
}

export function patientCautionBasis(p:Patient,title:string){
  const c=p.clinicalContext,href='/patients/'+encodeURIComponent(p.id)+'?tab=full#patient-context';
  return {rationale:[title==='Record completeness'?'The prototype did not identify a specific matching context pattern and shows its record-completeness fallback.':'The existing prototype scans recorded condition, context, and medication names/effects for matching text. This caution is a rule output, not an independently verified contraindication.'],sources:[{label:'Recorded condition',value:p.condition||'Not recorded',href},...c?[{label:'Clinical context',value:[c.medicalHistory,c.psychologicalContext,c.physicalContext,c.socialContext].filter(Boolean).join('\n')||'No relevant context recorded',date:c.date,href}]:[],...p.medications.filter(m=>m.effects).map(m=>({label:m.name+' · '+m.status+' · '+m.source,value:m.effects,date:m.reportedAt,href:'/patients/'+encodeURIComponent(p.id)+'?tab=visit#patient-medications'}))],considerations:['Review the underlying report, current medication list, prior tolerance, allergies, and missing clinical information before making a treatment decision.'],limitations:['No published guideline or drug interaction evidence is attached to this prototype rule. Its drug-specific statements require independent clinical verification.','The text scan can include historical medications and cannot establish current symptoms, causality, or suitability.']};
}
